# Generated by Django 3.1.8 on 2021-04-21 04:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_servicelist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceList',
            new_name='ServicePage',
        ),
    ]
