# Generated by Django 3.1.8 on 2021-04-21 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210421_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='description',
        ),
    ]
