# Generated by Django 3.1.8 on 2021-04-21 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0013_projectpage_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='project_description',
            field=models.TextField(default='sa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectpage',
            name='project_heading',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectpage',
            name='project_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='project_subheading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
