# Generated by Django 3.1.8 on 2021-04-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210421_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='about_body',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='about_description',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='about_heading',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='about_subheading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
