# Generated by Django 3.1.8 on 2021-04-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_contactdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdetail',
            old_name='contact_number',
            new_name='contact_number1',
        ),
        migrations.RenameField(
            model_name='contactdetail',
            old_name='contact_number_2',
            new_name='contact_number2',
        ),
        migrations.RenameField(
            model_name='contactdetail',
            old_name='contact_number_3',
            new_name='contact_number3',
        ),
        migrations.AddField(
            model_name='contactdetail',
            name='mail_address',
            field=models.EmailField(default='null', max_length=254),
            preserve_default=False,
        ),
    ]
